# Generated by Django 3.0 on 2025-10-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='INTERNSHIP',
        ),
        migrations.AddField(
            model_name='report',
            name='TASK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Task'),
            preserve_default=False,
        ),
    ]
